services:
  - type: web
    name: iptv-hls-streaming
    env: docker
    rootDir: prac5
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt
    healthCheckPath: /api/health
    buildArgs:
      - key: VIDEO1_ID
        value: 1v4vw1p4r9X51PgObR2NM_-MaAPFFwIjg
      - key: VIDEO2_ID
        value: 1ZxuU7gdChdpWPfbEBs7BFA39khcZGYaw
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
